"use client";

import { PredictionResult, CLASS_DISPLAY, CLASS_COLORS } from "@/types";
import { ShieldAlert, TrendingUp } from "lucide-react";

interface PredictionCardProps {
  result: PredictionResult;
}

const CLASS_DESCRIPTIONS: Record<string, string> = {
  glioma:
    "Gliomas are tumors that arise from glial cells in the brain or spinal cord.",
  meningioma:
    "Meningiomas are tumors that form on the membranes (meninges) surrounding the brain.",
  notumor:
    "No tumor detected by the model. The image does not appear to show a tumor.",
  pituitary:
    "Pituitary tumors develop in the pituitary gland at the base of the brain.",
};

export default function PredictionCard({ result }: PredictionCardProps) {
  const cls = result.prediction.class;
  const displayName = CLASS_DISPLAY[cls] ?? cls;
  const color = CLASS_COLORS[cls] ?? "#00d4ff";
  const confidence = result.prediction.confidence_percent;

  // Confidence tier
  const tier =
    confidence >= 85 ? { label: "High confidence", color: "text-emerald-400 border-emerald-500/30 bg-emerald-500/10" }
    : confidence >= 65 ? { label: "Moderate confidence", color: "text-amber-400 border-amber-500/30 bg-amber-500/10" }
    : { label: "Low confidence", color: "text-red-400 border-red-500/30 bg-red-500/10" };

  return (
    <div className="glass-card p-6 sm:p-8 animate-slide-up">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <p className="label-cyan mb-1">Classification Result</p>
          <h2 className="text-lg font-semibold text-slate-200">Diagnostic MRI Assessment</h2>
        </div>
        <TrendingUp className="w-5 h-5 text-slate-500" />
      </div>

      {/* Main result */}
      <div
        className="relative overflow-hidden rounded-2xl p-6 sm:p-8 mb-6 text-center"
        style={{
          background: `radial-gradient(ellipse at center, ${color}18 0%, transparent 70%)`,
          border: `1px solid ${color}40`,
        }}
      >
        <div
          className="text-xs font-mono uppercase tracking-[0.25em] mb-3 opacity-60"
          style={{ color }}
        >
          Detected Condition
        </div>
        <div
          className="text-4xl sm:text-5xl font-bold tracking-tight mb-4"
          style={{ color }}
        >
          {displayName}
        </div>

        {/* Confidence ring */}
        <div className="flex items-center justify-center gap-4">
          <div>
            <p className="text-slate-500 text-xs mb-1 uppercase tracking-wider">Confidence</p>
            <p className="text-3xl font-bold text-white">
              {confidence.toFixed(2)}
              <span className="text-lg text-slate-400">%</span>
            </p>
          </div>
        </div>

        {/* Confidence badge */}
        <div className="mt-4">
          <span className={`badge border text-xs ${tier.color}`}>
            {tier.label}
          </span>
        </div>
      </div>

      {/* Description */}
      <p className="text-sm text-slate-400 leading-relaxed mb-4">
        {CLASS_DESCRIPTIONS[cls]}
      </p>

      {/* Medical disclaimer mini */}
      <div className="flex items-start gap-2.5 px-4 py-3 rounded-xl bg-amber-500/5 border border-amber-500/20">
        <ShieldAlert className="w-4 h-4 text-amber-400 flex-shrink-0 mt-0.5" />
        <p className="text-xs text-amber-300/80 leading-snug">
          This result is generated by an AI research model and is{" "}
          <strong>not a medical diagnosis</strong>. Always consult a qualified healthcare
          professional or radiologist.
        </p>
      </div>
    </div>
  );
}
